services:
  nas-tools:
    image: coolkid903/nas-tools:latest
    ports:
      - 3010:3010
    volumes:
      - ./config:/config
      - /你的媒体目录:/你想设置的容器内能见到的目录
    user: "1000:1000"
    environment:
      - UMASK=000
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
